export const API = {
	CATALOG: {
		UNIT: {
			LIST: '/v1/catalog/unitofmeasure',
			CREATE: '/v1/catalog/unitofmeasure',
			UPDATE: '/v1/catalog/unitofmeasure',
			DELETES: '/v1/catalog/unitofmeasure',
			DELETE: (id: string) => `/v1/catalog/unitofmeasure/${id}`,
			DETAIL: (id: string) => `/v1/catalog/unitofmeasure/${id}`,
			IMPORT: '/v1/catalog/unitofmeasure/import',
			EXPORT: '/v1/catalog/unitofmeasure/export',
		},
		PROCESS: {
			GROUP: {
				LIST: '/v1/catalog/processgroup',
				CREATE: '/v1/catalog/processgroup',
				UPDATE: '/v1/catalog/processgroup',
				DELETES: '/v1/catalog/processgroup',
				DELETE: (id: string) => `/v1/catalog/processgroup/${id}`,
				DETAIL: (id: string) => `/v1/catalog/processgroup/${id}`,
				IMPORT: '/v1/catalog/processgroup/import',
				EXPORT: '/v1/catalog/processgroup/export',
			},
			STEP: {
				LIST: '/v1/catalog/productionprocess',
				CREATE: '/v1/catalog/productionprocess',
				UPDATE: '/v1/catalog/productionprocess',
				DELETES: '/v1/catalog/productionprocess',
				DELETE: (id: string) => `/v1/catalog/productionprocess/${id}`,
				DETAIL: (id: string) => `/v1/catalog/productionprocess/${id}`,
				IMPORT: '/v1/catalog/productionprocess/import',
				EXPORT: '/v1/catalog/productionprocess/export',
			},
		},
		CONTRACT_CODE: {
			LIST: '/v1/catalog/assignmentcode',
			CREATE: '/v1/catalog/assignmentcode',
			UPDATE: '/v1/catalog/assignmentcode',
			DELETES: '/v1/catalog/assignmentcode',
			DELETE: (id: string) => `/v1/catalog/assignmentcode/${id}`,
			DETAIL: (id: string) => `/v1/catalog/assignmentcode/${id}`,
			IMPORT: '/v1/catalog/assignmentcode/import',
			EXPORT: '/v1/catalog/assignmentcode/export',
		},
		ASSET: {
			LIST: '/v1/catalog/material',
			CREATE: '/v1/catalog/material',
			UPDATE: '/v1/catalog/material',
			DELETES: '/v1/catalog/material',
			DELETE: (id: string) => `/v1/catalog/material/${id}`,
			DETAIL: (id: string) => `/v1/catalog/material/${id}`,
			IMPORT: '/v1/catalog/material/import',
			EXPORT: '/v1/catalog/material/export',
		},
		EQUIPMENT: {
			LIST: '/v1/catalog/equipment',
			CREATE: '/v1/catalog/equipment',
			UPDATE: '/v1/catalog/equipment',
			DELETES: '/v1/catalog/equipment',
			DELETE: (id: string) => `/v1/catalog/equipment/${id}`,
			DETAIL: (id: string) => `/v1/catalog/equipment/${id}`,
			EQUIPMENT_PARTS: (id: string) => `/v1/catalog/equipment/${id}/parts`,
			IMPORT: '/v1/catalog/equipment/import',
			EXPORT: '/v1/catalog/equipment/export',
		},
		PART: {
			LIST: '/v1/catalog/part',
			CREATE: '/v1/catalog/part',
			UPDATE: '/v1/catalog/part',
			DELETES: '/v1/catalog/part',
			DELETE: (id: string) => `/v1/catalog/part/${id}`,
			DETAIL: (id: string) => `/v1/catalog/part/${id}`,
			PART_EQUIPMENT: (id: string) => `/v1/catalog/part/${id}/equipments`,
			IMPORT: '/v1/catalog/part/import',
			EXPORT: '/v1/catalog/part/export',
		},
		OTHER_PART: {
			LIST: '/v1/catalog/otherpart',
			CREATE: '/v1/catalog/otherpart',
			UPDATE: '/v1/catalog/otherpart',
			DELETES: '/v1/catalog/otherpart',
			DETAIL: (id: string) => `/v1/catalog/otherpart/${id}`,
			IMPORT: '/v1/catalog/otherpart/import',
			EXPORT: '/v1/catalog/otherpart/export',
		},
		PRODUCT: {
			LIST: '/v1/catalog/product',
			CREATE: '/v1/catalog/product',
			UPDATE: '/v1/catalog/product',
			DELETES: '/v1/catalog/product',
			DELETE: (id: string) => `/v1/catalog/product/${id}`,
			DETAIL: (id: string) => `/v1/catalog/product/${id}`,
			IMPORT: '/v1/catalog/product/import',
			EXPORT: '/v1/catalog/product/export',
		},
		PARAMETER: {
			PASSPORT: {
				LIST: '/v1/catalog/passport',
				CREATE: '/v1/catalog/passport',
				UPDATE: '/v1/catalog/passport',
				DELETES: '/v1/catalog/passport',
				DELETE: (id: string) => `/v1/catalog/passport/${id}`,
				DETAIL: (id: string) => `/v1/catalog/passport/${id}`,
				IMPORT: '/v1/catalog/passport/import',
				EXPORT: '/v1/catalog/passport/export',
			},
			STRENGTH: {
				LIST: '/v1/catalog/hardness',
				CREATE: '/v1/catalog/hardness',
				UPDATE: '/v1/catalog/hardness',
				DELETES: '/v1/catalog/hardness',
				DELETE: (id: string) => `/v1/catalog/hardness/${id}`,
				DETAIL: (id: string) => `/v1/catalog/hardness/${id}`,
				IMPORT: '/v1/catalog/hardness/import',
				EXPORT: '/v1/catalog/hardness/export',
			},
			CLAMP: {
				LIST: '/v1/catalog/stoneclampratio',
				CREATE: '/v1/catalog/stoneclampratio',
				UPDATE: '/v1/catalog/stoneclampratio',
				DELETES: '/v1/catalog/stoneclampratio',
				DELETE: (id: string) => `/v1/catalog/stoneclampratio/${id}`,
				DETAIL: (id: string) => `/v1/catalog/stoneclampratio/${id}`,
				IMPORT: '/v1/catalog/stoneclampratio/import',
				EXPORT: '/v1/catalog/stoneclampratio/export',
			},
			INSERT: {
				LIST: '/v1/catalog/insertitem',
				CREATE: '/v1/catalog/insertitem',
				UPDATE: '/v1/catalog/insertitem',
				DELETES: '/v1/catalog/insertitem',
				DELETE: (id: string) => `/v1/catalog/insertitem/${id}`,
				DETAIL: (id: string) => `/v1/catalog/insertitem/${id}`,
				IMPORT: '/v1/catalog/insertitem/import',
				EXPORT: '/v1/catalog/insertitem/export',
			},
			TECHNOLOGY: {
				LIST: '/v1/catalog/technology',
				CREATE: '/v1/catalog/technology',
				UPDATE: '/v1/catalog/technology',
				DELETES: '/v1/catalog/technology',
				DELETE: (id: string) => `/v1/catalog/technology/${id}`,
				DETAIL: (id: string) => `/v1/catalog/technology/${id}`,
				IMPORT: '/v1/catalog/technology/import',
				EXPORT: '/v1/catalog/technology/export',
			},
			LONGWALLPARAMETERS: {
				LIST: '/v1/catalog/longwallparameters',
				CREATE: '/v1/catalog/longwallparameters',
				UPDATE: '/v1/catalog/longwallparameters',
				DELETES: '/v1/catalog/longwallparameters',
				DELETE: (id: string) => `/v1/catalog/longwallparameters/${id}`,
				DETAIL: (id: string) => `/v1/catalog/longwallparameters/${id}`,
				IMPORT: '/v1/catalog/longwallparameters/import',
				EXPORT: '/v1/catalog/longwallparameters/export',
			},
			CUTTINGTHICKNESS: {
				LIST: '/v1/catalog/cuttingthickness',
				CREATE: '/v1/catalog/cuttingthickness',
				UPDATE: '/v1/catalog/cuttingthickness',
				DELETES: '/v1/catalog/cuttingthickness',
				DELETE: (id: string) => `/v1/catalog/cuttingthickness/${id}`,
				DETAIL: (id: string) => `/v1/catalog/cuttingthickness/${id}`,
				IMPORT: '/v1/catalog/cuttingthickness/import',
				EXPORT: '/v1/catalog/cuttingthickness/export',
			},
			SEAMFACE: {
				LIST: '/v1/catalog/seamface',
				CREATE: '/v1/catalog/seamface',
				UPDATE: '/v1/catalog/seamface',
				DELETES: '/v1/catalog/seamface',
				DELETE: (id: string) => `/v1/catalog/seamface/${id}`,
				DETAIL: (id: string) => `/v1/catalog/seamface/${id}`,
				IMPORT: '/v1/catalog/seamface/import',
				EXPORT: '/v1/catalog/seamface/export',
			},
			STEP: {
				LIST: '/v1/catalog/supportstep',
				CREATE: '/v1/catalog/supportstep',
				UPDATE: '/v1/catalog/supportstep',
				DELETES: '/v1/catalog/supportstep',
				DELETE: (id: string) => `/v1/catalog/supportstep/${id}`,
				DETAIL: (id: string) => `/v1/catalog/supportstep/${id}`,
				IMPORT: '/v1/catalog/supportstep/import',
				EXPORT: '/v1/catalog/supportstep/export',
			},
			PRODUCTION_ORDER: {
				LIST: '/v1/catalog/productionorder',
				CREATE: '/v1/catalog/productionorder',
				UPDATE: '/v1/catalog/productionorder',
				DELETES: '/v1/catalog/productionorder',
				DELETE: (id: string) => `/v1/catalog/productionorder/${id}`,
				DETAIL: (id: string) => `/v1/catalog/productionorder/${id}`,
				IMPORT: '/v1/catalog/productionorder/import',
				EXPORT: '/v1/catalog/productionorder/export',
			},
			POWER: {
				LIST: '/v1/catalog/power',
				CREATE: '/v1/catalog/power',
				UPDATE: '/v1/catalog/power',
				DELETES: '/v1/catalog/power',
				DELETE: (id: string) => `/v1/catalog/power/${id}`,
				DETAIL: (id: string) => `/v1/catalog/power/${id}`,
				IMPORT: '/v1/catalog/power/import',
				EXPORT: '/v1/catalog/power/export',
			},
		},
		ADJUSTMENT: {
			FACTOR: {
				LIST: '/v1/catalog/adjustmentfactor',
				CREATE: '/v1/catalog/adjustmentfactor',
				UPDATE: '/v1/catalog/adjustmentfactor',
				DELETES: '/v1/catalog/adjustmentfactor',
				DELETE: (id: string) => `/v1/catalog/adjustmentfactor/${id}`,
				DETAIL: (id: string) => `/v1/catalog/adjustmentfactor/${id}`,
				DETAILS: '/v1/catalog/adjustmentfactor/details',
				IMPORT: '/v1/catalog/adjustmentfactor/import',
				EXPORT: '/v1/catalog/adjustmentfactor/export',
			},
			INTERPRETER: {
				LIST: '/v1/catalog/adjustmentfactordescription',
				CREATE: '/v1/catalog/adjustmentfactordescription',
				UPDATE: '/v1/catalog/adjustmentfactordescription',
				DELETES: '/v1/catalog/adjustmentfactordescription',
				DELETE: (id: string) => `/v1/catalog/adjustmentfactordescription/${id}`,
				DETAIL: (id: string) => `/v1/catalog/adjustmentfactordescription/${id}`,
				IMPORT: '/v1/catalog/adjustmentfactordescription/import',
				EXPORT: '/v1/catalog/adjustmentfactordescription/export',
			},
		},

		NORM_FACTOR: {
			LIST: '/v1/catalog/normfactor',
			CREATE: '/v1/catalog/normfactor',
			UPDATE: '/v1/catalog/normfactor',
			DELETES: '/v1/catalog/normfactor',
			DETAIL: (id: string) => `/v1/catalog/normfactor/${id}`,
			IMPORT: '/v1/catalog/normfactor/import',
			EXPORT: '/v1/catalog/normfactor/export',
		},
	},

	DASHBOARD: {
		COST_SUMMARY: '/v1/dashboard/cost-summary',
	},

	PRICING: {
		MATERIAL: {
			ALL: '/v1/pricing/materialunitprice/all',
			TUNNELING: {
				LIST: '/v1/pricing/materialunitprice',
				CREATE: '/v1/pricing/materialunitprice',
				UPDATE: '/v1/pricing/materialunitprice',
				DELETES: '/v1/pricing/materialunitpricelist',
				DELETE: (id: string) => `/v1/pricing/materialunitprice/${id}`,
				DETAIL: (id: string) => `/v1/pricing/materialunitprice/${id}`,
				IMPORT: '/v1/pricing/materialunitprice/import',
				EXPORT: '/v1/pricing/materialunitprice/export',
			},
			LONGWALL_PANEL: {
				LIST: '/v1/pricing/longwallmaterialunitprice',
				CREATE: '/v1/pricing/longwallmaterialunitprice',
				UPDATE: '/v1/pricing/longwallmaterialunitprice',
				DELETES: '/v1/pricing/longwallmaterialunitpricelist',
				DELETE: (id: string) => `/v1/pricing/longwallmaterialunitprice/${id}`,
				DETAIL: (id: string) => `/v1/pricing/longwallmaterialunitprice/${id}`,
				IMPORT: '/v1/pricing/longwallmaterialunitprice/import',
				EXPORT: '/v1/pricing/longwallmaterialunitprice/export',
			},
			SUPPORT_AND_DRILLING: {
				LIST: '/v1/pricing/tunnelsupportanddrillingmaterialunitprice',
				CREATE: '/v1/pricing/tunnelsupportanddrillingmaterialunitprice',
				UPDATE: '/v1/pricing/tunnelsupportanddrillingmaterialunitprice',
				DELETES: '/v1/pricing/tunnelsupportanddrillingmaterialunitpricelist',
				DELETE: (id: string) =>
					`/v1/pricing/tunnelsupportanddrillingmaterialunitprice/${id}`,
				DETAIL: (id: string) =>
					`/v1/pricing/tunnelsupportanddrillingmaterialunitprice/${id}`,
				IMPORT: '/v1/pricing/tunnelsupportanddrillingmaterialunitprice/import',
				EXPORT: '/v1/pricing/tunnelsupportanddrillingmaterialunitprice/export',
			},
		},
		SLIDE: {
			LIST: '/v1/pricing/slideunitprice',
			CREATE: '/v1/pricing/slideunitprice',
			UPDATE: '/v1/pricing/slideunitprice',
			DELETES: '/v1/pricing/slideunitprice',
			DELETE: (id: string) => `/v1/pricing/slideunitprice/${id}`,
			DETAIL: (id: string) => `/v1/pricing/slideunitprice/${id}`,
			DETAIL_LIST: `/v1/pricing/slideunitprice/details`,
			IMPORT: '/v1/pricing/slideunitprice/import',
			EXPORT: '/v1/pricing/slideunitprice/export',
		},
		MAINTENANCE: {
			LIST: '/v1/pricing/maintainunitpriceequipment',
			CREATE: '/v1/pricing/maintainunitpriceequipment',
			UPDATE: '/v1/pricing/maintainunitpriceequipment',
			DELETES: '/v1/pricing/maintainunitpriceequipment',
			DELETE: (id: string) => `/v1/pricing/maintainunitpriceequipment/${id}`,
			DETAIL: (id: string) => `/v1/pricing/maintainunitpriceequipment/${id}`,
			TUNNEL_IMPORT: '/v1/pricing/tunnelmaintainunitpriceequipment/import',
			TUNNEL_EXPORT: '/v1/pricing/tunnelmaintainunitpriceequipment/export',
			LONGWALL_IMPORT: '/v1/pricing/longwallmaintainunitpriceequipment/import',
			LONGWALL_EXPORT: '/v1/pricing/longwallmaintainunitpriceequipment/export',
		},
		ELECTRICITY: {
			TUNNELING: {
				LIST: '/v1/pricing/tunnelelectricityunitpriceequipment',
				CREATE: '/v1/pricing/tunnelelectricityunitpriceequipment',
				UPDATE: '/v1/pricing/tunnelelectricityunitpriceequipment',
				DELETES: '/v1/pricing/electricityunitpriceequipment',
				DELETE: (id: string) =>
					`/v1/pricing/tunnelelectricityunitpriceequipment/${id}`,
				DETAIL: (id: string) =>
					`/v1/pricing/tunnelelectricityunitpriceequipment/${id}`,
				IMPORT: '/v1/pricing/tunnelelectricityunitpriceequipment/import',
				EXPORT: '/v1/pricing/tunnelelectricityunitpriceequipment/export',
			},
			LONGWALL_PANEL: {
				LIST: '/v1/pricing/longwallelectricityunitpriceequipment',
				CREATE: '/v1/pricing/longwallelectricityunitpriceequipment',
				UPDATE: '/v1/pricing/longwallelectricityunitpriceequipment',
				DELETES: '/v1/pricing/electricityunitpriceequipment',
				DELETE: (id: string) =>
					`/v1/pricing/longwallelectricityunitpriceequipment/${id}`,
				DETAIL: (id: string) =>
					`/v1/pricing/longwallelectricityunitpriceequipment/${id}`,
				IMPORT: '/v1/pricing/longwallelectricityunitpriceequipment/import',
				EXPORT: '/v1/pricing/longwallelectricityunitpriceequipment/export',
			},
		},
	},

	COST: {
		PRODUCT: {
			LIST: '/v1/pricing/productunitprice',
			CREATE: '/v1/pricing/productunitprice',
			UPDATE: '/v1/pricing/productunitprice',
			DELETES: '/v1/pricing/productunitprice',
			EXPORT: '/v1/pricing/productunitprice/export',
			EXPORT_ADJUSTMENT_ELECTRICITY_MAINTAIN_REPORT:
				'/v1/pricing/productunitprice/export-adjustment-electricity-maintain-report',
			DELETE: (id: string) => `/v1/pricing/productunitprice/${id}`,
			DETAIL_PLANNED: (id: string) =>
				`/v1/pricing/productunitprice/planned/${id}`,
			DETAIL_ACTUAL: (id: string) =>
				`/v1/pricing/productunitprice/actual/${id}`,
			DETAIL_ADJUSTMENT: (id: string) =>
				`/v1/pricing/productunitprice/adjustment/${id}`,
			UPDATE_ADJUSTMENT: '/v1/pricing/productunitprice/adjustment',
		},
		PLANNED_MATERIAL: {
			CREATE: '/v1/pricing/plannedmaterialcost',
			UPDATE: '/v1/pricing/plannedmaterialcost',
			DELETES: '/v1/pricing/plannedmaterialcost',
			DETAIL: (id: string) => `/v1/pricing/plannedmaterialcost/${id}`,
		},
		PLANNED_MAINTAIN: {
			CREATE: '/v1/pricing/plannedmaintaincost',
			UPDATE: '/v1/pricing/plannedmaintaincost',
			DELETES: '/v1/pricing/plannedmaintaincost',
			DETAIL: (id: string) => `/v1/pricing/plannedmaintaincost/${id}`,
		},
		PLANNED_ELECTRICITY: {
			CREATE: '/v1/pricing/plannedelectricitycost',
			UPDATE: '/v1/pricing/plannedelectricitycost',
			DELETES: '/v1/pricing/plannedelectricitycost',
			DETAIL: (id: string) => `/v1/pricing/plannedelectricitycost/${id}`,
		},

		ACTUAL_MATERIAL: {
			CREATE: '/v1/pricing/actualmaterialcost',
			UPDATE: '/v1/pricing/actualmaterialcost',
			DELETES: '/v1/pricing/actualmaterialcost',
			DEATAIL: (id: string) => `/v1/pricing/actualmaterialcost/${id}`,
		},
		ACTUAL_MAINTAIN: {
			CREATE: '/v1/pricing/actualmaintaincost',
			UPDATE: '/v1/pricing/actualmaintaincost',
			DELETES: '/v1/pricing/actualmaintaincost',
			DETAIL: (id: string) => `/v1/pricing/actualmaintaincost/${id}`,
		},
		ACTUAL_ELECTRICITY: {
			CREATE: '/v1/pricing/actualelectricitycost',
			UPDATE: '/v1/pricing/actualelectricitycost',
			DELETES: '/v1/pricing/actualelectricitycost',
			DETAIL: (id: string) => `/v1/pricing/actualelectricitycost/${id}`,
		},
		ADJUSTMENT_MATERIAL: {
			DETAIL: (id: string) => `/v1/pricing/adjustmnetmaterialcost/${id}`,
		},
		ADJUSTMENT_MAINTAIN: {
			DETAIL: (id: string) => `/v1/pricing/adjustmentmaintaincost/${id}`,
		},
		ADJUSTMENT_ELECTRICITY: {
			DETAIL: (id: string) => `/v1/pricing/adjustmentelectricitycost/${id}`,
		},
		LUMP_SUM_FINAL_SETTLEMENT: {
			LIST: '/v1/pricing/lump-sum-final-settlement/list',
			QUARTER_LIST: '/v1/pricing/lump-sum-final-settlement/quarter-list',
			QUARTER_EXPORT:
				'/v1/pricing/lump-sum-final-settlement/quarter-export',
			QUARTER_CUSTOM_COST_LIST:
				'/v1/pricing/lump-sum-final-settlement/quarter-custom-cost/list',
			QUARTER_CUSTOM_COST_CREATE:
				'/v1/pricing/lump-sum-final-settlement/quarter-custom-cost',
			QUARTER_CUSTOM_COST_UPDATE:
				'/v1/pricing/lump-sum-final-settlement/quarter-custom-cost',
			QUARTER_CUSTOM_COST_DELETE: (id: string) =>
				`/v1/pricing/lump-sum-final-settlement/quarter-custom-cost/${id}`,
		},
	},

	PRODUCTION: {
		PRODUCTION_OUTPUT: {
			LIST: '/v1/production/productionoutput',
			CREATE: '/v1/production/productionoutput',
			CREATE_LIST: '/v1/production/productionoutputlist',
			UPDATE: '/v1/production/productionoutput',
			UPDATE_LIST: '/v1/production/productionoutputlist',
			DELETE: (id: string) => `/v1/production/productionoutput/${id}`,
			RAW_DETAIL: (id: string) => `/v1/production/productionoutput/${id}`,
			DETAIL: (id: string) => `/v1/production/productionoutput/${id}/detail`,
			DELETES: `/v1/production/productionoutput`,
		},
		ACCEPTANCE_REPORT: {
			UPLOAD_FILE: (productionOutputId: string) =>
				`/v1/production/acceptancereport/uploadfile/${productionOutputId}`,
			CREATE: '/v1/production/acceptancereport',
			RAW_DETAIL: (id: string) => `/v1/production/acceptancereport/${id}`,
			UPDATE: '/v1/production/acceptancereport',
			DOWNLOAD: (id: string) =>
				`/v1/production/acceptancereport/${id}/download`,
			EXPORT_PERIOD: (month: string, year: string) =>
				`/v1/production/acceptancereport/export?month=${month}&year=${year}`,
			EXPORT_LONG_TERM_MATERIAL_COST: (id: string) =>
				`/v1/production/acceptancereport/${id}/export-longterm-material-cost`,
			ADDITIONAL_COST_LIST: (id: string) =>
				`/v1/production/acceptancereport/${id}/additional-cost`,
			LONG_TERM_TRACKING_LIST: (id: string) =>
				`/v1/production/acceptancereport/${id}/long-term-tracking`,
			LONG_TERM_TRACKING_DETAIL: (id: string) =>
				`/v1/production/acceptancereport/${id}/long-term-tracking/detail`,
			UPDATE_LONG_TERM_TRACKING:
				'/v1/production/acceptancereport/long-term-tracking/list',
		},
	},

	AUTH: {
		SIGN_IN: '/v1/tokens',
		REFRESH: '/v1/tokens/refresh',
	},
} as const;
