export const PERMISSIONS = {
	REPORT: {
		SCTX_REVENUE_BY_ASSIGNMENT_CODE: {
			EXPORT: 'report.sctx-revenue-by-assignment-code.export',
		},
		PRODUCT_UNIT_PRICE: {
			EXPORT: 'report.productunitprice.export',
		},
		LUMP_SUM_FINAL_SETTLEMENT: {
			EXPORT: 'report.lumpsumfinalsettlement.export',
		},
		ACCEPTANCE_REPORT: {
			EXPORT: 'report.acceptancereport.export',
		},
		LONG_TERM_TRACKING: {
			EXPORT: 'report.long-term-tracking.export',
		},
	},
	PRODUCTION: {
		ACCEPTANCE_REPORT: {
			EXPORT: 'production.acceptancereport.export',
		},
	},
	CATALOG: {
		DEPARTMENT: {
			READ: 'catalog.department.read',
			CREATE: 'catalog.department.create',
			UPDATE: 'catalog.department.update',
			DELETE: 'catalog.department.delete',
			IMPORT: 'catalog.department.import',
			EXPORT: 'catalog.department.export',
		},
		EMPLOYEE: {
			READ: 'catalog.employee.read',
			CREATE: 'catalog.employee.create',
			UPDATE: 'catalog.employee.update',
			DELETE: 'catalog.employee.delete',
			IMPORT: 'catalog.employee.import',
			EXPORT: 'catalog.employee.export',
		},
		POSITION: {
			READ: 'catalog.position.read',
			CREATE: 'catalog.position.create',
			UPDATE: 'catalog.position.update',
			DELETE: 'catalog.position.delete',
			IMPORT: 'catalog.position.import',
			EXPORT: 'catalog.position.export',
		},
		UNIT: {
			READ: 'catalog.unitofmeasure.read',
			CREATE: 'catalog.unitofmeasure.create',
			UPDATE: 'catalog.unitofmeasure.update',
			DELETE: 'catalog.unitofmeasure.delete',
			IMPORT: 'catalog.unitofmeasure.import',
			EXPORT: 'catalog.unitofmeasure.export',
		},
		CONTRACT_CODE: {
			READ: 'catalog.assignmentcode.read',
			CREATE: 'catalog.assignmentcode.create',
			UPDATE: 'catalog.assignmentcode.update',
			DELETE: 'catalog.assignmentcode.delete',
			IMPORT: 'catalog.assignmentcode.import',
			EXPORT: 'catalog.assignmentcode.export',
		},
		ASSET: {
			READ: 'catalog.material.read',
			CREATE: 'catalog.material.create',
			UPDATE: 'catalog.material.update',
			DELETE: 'catalog.material.delete',
			IMPORT: 'catalog.material.import',
			EXPORT: 'catalog.material.export',
		},
		EQUIPMENT: {
			READ: 'catalog.equipment.read',
			CREATE: 'catalog.equipment.create',
			UPDATE: 'catalog.equipment.update',
			DELETE: 'catalog.equipment.delete',
			IMPORT: 'catalog.equipment.import',
			EXPORT: 'catalog.equipment.export',
		},
		PART_MAIN: {
			READ: 'catalog.part.read',
			CREATE: 'catalog.part.create',
			UPDATE: 'catalog.part.update',
			DELETE: 'catalog.part.delete',
			IMPORT: 'catalog.part.import',
			EXPORT: 'catalog.part.export',
		},
		PART_OTHER: {
			READ: 'catalog.otherpart.read',
			CREATE: 'catalog.otherpart.create',
			UPDATE: 'catalog.otherpart.update',
			DELETE: 'catalog.otherpart.delete',
			IMPORT: 'catalog.otherpart.import',
			EXPORT: 'catalog.otherpart.export',
		},
		PRODUCT: {
			READ: 'catalog.product.read',
			CREATE: 'catalog.product.create',
			UPDATE: 'catalog.product.update',
			DELETE: 'catalog.product.delete',
			IMPORT: 'catalog.product.import',
			EXPORT: 'catalog.product.export',
		},
		PRODUCTION_ORDER: {
			READ: 'catalog.productionorder.read',
			CREATE: 'catalog.productionorder.create',
			UPDATE: 'catalog.productionorder.update',
			DELETE: 'catalog.productionorder.delete',
			IMPORT: 'catalog.productionorder.import',
			EXPORT: 'catalog.productionorder.export',
		},
		PROCESS_GROUP: {
			READ: 'catalog.processgroup.read',
			CREATE: 'catalog.processgroup.create',
			UPDATE: 'catalog.processgroup.update',
			DELETE: 'catalog.processgroup.delete',
			IMPORT: 'catalog.processgroup.import',
			EXPORT: 'catalog.processgroup.export',
		},
		PROCESS_STEP: {
			READ: 'catalog.productionprocess.read',
			CREATE: 'catalog.productionprocess.create',
			UPDATE: 'catalog.productionprocess.update',
			DELETE: 'catalog.productionprocess.delete',
			IMPORT: 'catalog.productionprocess.import',
			EXPORT: 'catalog.productionprocess.export',
		},
		PARAMETER_PASSPORT: {
			READ: 'catalog.passport.read',
			CREATE: 'catalog.passport.create',
			UPDATE: 'catalog.passport.update',
			DELETE: 'catalog.passport.delete',
			IMPORT: 'catalog.passport.import',
			EXPORT: 'catalog.passport.export',
		},
		PARAMETER_HARDNESS: {
			READ: 'catalog.hardness.read',
			CREATE: 'catalog.hardness.create',
			UPDATE: 'catalog.hardness.update',
			DELETE: 'catalog.hardness.delete',
			IMPORT: 'catalog.hardness.import',
			EXPORT: 'catalog.hardness.export',
		},
		PARAMETER_STONE_CLAMP_RATIO: {
			READ: 'catalog.stoneclampratio.read',
			CREATE: 'catalog.stoneclampratio.create',
			UPDATE: 'catalog.stoneclampratio.update',
			DELETE: 'catalog.stoneclampratio.delete',
			IMPORT: 'catalog.stoneclampratio.import',
			EXPORT: 'catalog.stoneclampratio.export',
		},
		PARAMETER_INSERT_ITEM: {
			READ: 'catalog.insertitem.read',
			CREATE: 'catalog.insertitem.create',
			UPDATE: 'catalog.insertitem.update',
			DELETE: 'catalog.insertitem.delete',
			IMPORT: 'catalog.insertitem.import',
			EXPORT: 'catalog.insertitem.export',
		},
		PARAMETER_TECHNOLOGY: {
			READ: 'catalog.technology.read',
			CREATE: 'catalog.technology.create',
			UPDATE: 'catalog.technology.update',
			DELETE: 'catalog.technology.delete',
			IMPORT: 'catalog.technology.import',
			EXPORT: 'catalog.technology.export',
		},
		PARAMETER_LONGWALL: {
			READ: 'catalog.longwallparameters.read',
			CREATE: 'catalog.longwallparameters.create',
			UPDATE: 'catalog.longwallparameters.update',
			DELETE: 'catalog.longwallparameters.delete',
			IMPORT: 'catalog.longwallparameters.import',
			EXPORT: 'catalog.longwallparameters.export',
		},
		PARAMETER_CUTTING_THICKNESS: {
			READ: 'catalog.cuttingthickness.read',
			CREATE: 'catalog.cuttingthickness.create',
			UPDATE: 'catalog.cuttingthickness.update',
			DELETE: 'catalog.cuttingthickness.delete',
			IMPORT: 'catalog.cuttingthickness.import',
			EXPORT: 'catalog.cuttingthickness.export',
		},
		PARAMETER_SEAM_FACE: {
			READ: 'catalog.seamface.read',
			CREATE: 'catalog.seamface.create',
			UPDATE: 'catalog.seamface.update',
			DELETE: 'catalog.seamface.delete',
			IMPORT: 'catalog.seamface.import',
			EXPORT: 'catalog.seamface.export',
		},
		PARAMETER_STEP: {
			READ: 'catalog.supportstep.read',
			CREATE: 'catalog.supportstep.create',
			UPDATE: 'catalog.supportstep.update',
			DELETE: 'catalog.supportstep.delete',
			IMPORT: 'catalog.supportstep.import',
			EXPORT: 'catalog.supportstep.export',
		},
		PARAMETER_POWER: {
			READ: 'catalog.power.read',
			CREATE: 'catalog.power.create',
			UPDATE: 'catalog.power.update',
			DELETE: 'catalog.power.delete',
			IMPORT: 'catalog.power.import',
			EXPORT: 'catalog.power.export',
		},
		ADJUSTMENT_FACTOR: {
			READ: 'catalog.adjustmentfactor.read',
			CREATE: 'catalog.adjustmentfactor.create',
			UPDATE: 'catalog.adjustmentfactor.update',
			DELETE: 'catalog.adjustmentfactor.delete',
			IMPORT: 'catalog.adjustmentfactor.import',
			EXPORT: 'catalog.adjustmentfactor.export',
		},
		ADJUSTMENT_FACTOR_DESC: {
			READ: 'catalog.adjustmentfactordescription.read',
			CREATE: 'catalog.adjustmentfactordescription.create',
			UPDATE: 'catalog.adjustmentfactordescription.update',
			DELETE: 'catalog.adjustmentfactordescription.delete',
			IMPORT: 'catalog.adjustmentfactordescription.import',
			EXPORT: 'catalog.adjustmentfactordescription.export',
		},
		SAVINGS_RATE: {
			READ: 'catalog.savingsrateconfig.read',
			CREATE: 'catalog.savingsrateconfig.create',
			UPDATE: 'catalog.savingsrateconfig.update',
			DELETE: 'catalog.savingsrateconfig.delete',
			IMPORT: 'catalog.savingsrateconfig.import',
			EXPORT: 'catalog.savingsrateconfig.export',
		},
		AK_FACTOR: {
			READ: 'catalog.akfactorconfig.read',
			CREATE: 'catalog.akfactorconfig.create',
			UPDATE: 'catalog.akfactorconfig.update',
			DELETE: 'catalog.akfactorconfig.delete',
			IMPORT: 'catalog.akfactorconfig.import',
			EXPORT: 'catalog.akfactorconfig.export',
		},
		REVENUE_COST: {
			READ: 'catalog.revenuecostadjustmentconfig.read',
			CREATE: 'catalog.revenuecostadjustmentconfig.create',
			UPDATE: 'catalog.revenuecostadjustmentconfig.update',
			DELETE: 'catalog.revenuecostadjustmentconfig.delete',
			IMPORT: 'catalog.revenuecostadjustmentconfig.import',
			EXPORT: 'catalog.revenuecostadjustmentconfig.export',
		},
		NORM_FACTOR: {
			READ: 'catalog.normfactor.read',
			CREATE: 'catalog.normfactor.create',
			UPDATE: 'catalog.normfactor.update',
			DELETE: 'catalog.normfactor.delete',
			IMPORT: 'catalog.normfactor.import',
			EXPORT: 'catalog.normfactor.export',
		},
	},
	SYSTEM: {
		PERMISSION: {
			READ: 'system.permission.read',
			UPDATE: 'system.permission.update',
		},
		FIXKEY: {
			READ: 'system.fixkey.read',
			UPDATE: 'system.fixkey.update',
		},
	},
} as const;
